=== chinayuans/sysadmin/src/common/org/appfuse/common/util/xml/sax/read/commondb_migration.dtd
<!ELEMENT commondb_migration (component)*>
<!ELEMENT component (script_group)*>
<!ATTLIST component name CDATA #IMPLIED>
<!ELEMENT script_group (script)*>
<!ATTLIST script_group old_ver CDATA #REQUIRED>
<!ELEMENT script (#PCDATA)>
<!ATTLIST script new_ver CDATA #REQUIRED>

=== chinayuans/sysadmin/WebRoot/WEB-INF/classes/org/appfuse/common/util/xml/sax/read/commondb_migration.xml
<?xml version = "1.0"?>
<!DOCTYPE commondb_migration SYSTEM "file:/D:/work/eclipse3.1-work/work/sysadmin/WebRoot/WEB-INF/classes/org/appfuse/common/util/xml/sax/read/commondb_migration.dtd"
	[
		<!ENTITY cost "40">
		<!ENTITY address SYSTEM "file:/D:/work/eclipse3.1-work/work/sysadmin/WebRoot/WEB-INF/classes/org/appfuse/common/util/xml/sax/read/address.txt">
]>

<!-- commondb_migratin indicates it is a root elment in the xml. -->
<!-- "commondb_migration.dtd" indicates it is a systemId in the xml. -->

<commondb_migration>
	<component name="recovery.ejb">
		<!-- the script_groups should be sorted upward by old_ver -->
		<script_group old_ver="6.0.1.*">
			<!-- the scripts should be sorted downward by new_ver -->
			<script new_ver="6.1.0.0">
				upgradeSchema601_Recovery.sql
			</script>
			<script new_ver="mess">
				cost: &cost; address: &address;
				<![CDATA[The amount is >10000 now]]>
			</script>
		</script_group>
		<script_group old_ver="6.0.2.*">
			<script new_ver="6.1.0.0">
				upgradeSchema602_Recovery.sql
			</script>
		</script_group>
	</component>
	<component name="interfaceMediation" />
	<component name="relationshipService">
		<!-- the script_groups should be sorted upward by old_ver -->
		<script_group old_ver="6.0.1.*">
			<!-- the scripts should be sorted downward by new_ver -->
			<script new_ver="6.1.0.0">
				createTable_RelationshipMetadataTable.sql
			</script>
		</script_group>
		<script_group old_ver="6.0.2.*">
			<script new_ver="6.1.0.0">
				createTable_RelationshipMetadataTable.sql
			</script>
		</script_group>
	</component>
	<component name="scheduler.wbi" />
	<component name="customization">
		<!-- the script_groups should be sorted upward by old_ver -->
		<script_group old_ver="6.0.1.*">
			<!-- the scripts should be sorted downward by new_ver -->
			<script new_ver="6.1.0.0">
				upgradeSchema601_customization.sql
			</script>
		</script_group>
		<script_group old_ver="6.0.2.*">
			<script new_ver="6.1.0.0">
				upgradeSchema602_customization.sql
			</script>
		</script_group>
	</component>
	<component name="persistentlockmanager">
		<!-- the script_groups should be sorted upward by old_ver -->
		<script_group old_ver="6.0.1.*">
			<!-- the scripts should be sorted downward by new_ver -->
			<script new_ver="6.1.0.0">
				upgradeSchema601_lockmanager.sql
			</script>
		</script_group>
	</component>
</commondb_migration>
